name: .NET - Continuous integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  dotnet_continuous_integration:
    # Pinning to a specific Ubuntu version to have reproducible builds (at least, more than with ubuntu-latest)
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.7

    - name: Setup .NET with the version defined in global.json
      uses: actions/setup-dotnet@v4.0.1
      with:
        # Cache NuGet packages, calculating their hash from `packages.lock.json` as part of the cache key
        cache: true
        cache-dependency-path: 'src/**/packages.lock.json'

    - name: Install just, a command runner # just is used in the next steps
      uses: extractions/setup-just@v2
      with:
        just-version: 1.29.1

    - name: Restore dependencies of the solution without updating `packages.lock.json`
      run: just restore

    - name: Verify that all code of the solution is correctly formatted
      run: just format

    - name: Build the solution without restoring its dependencies
      run: just build

    - name: Run tests for the solution without building it
      run: just test
